version: '3'

services:
  search:
    image: getmeili/meilisearch
    ports:
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY=secret
    volumes:
      - meili-data:/meili_data

volumes:
  meili-data:
